name: Build and Deploy

on: 
  workflow_dispatch:
  push:
    branches:
     - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: shalzz/zola-deploy-action@v0.20.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}